### ISSUE TITLE
ModuleNotFoundError: No module named 'down'

### ISSUE THREAD

**Issue by leonheess** [halilozercan/paralleldownload#13]
Starting PGet 0.5 I get: 

```
File ".../python-environments/lib/python3.7/site-packages/pget/__init__.py", line 1, in <module>
    from down.py import Downloader
ModuleNotFoundError: No module named 'down'
```

**Comment by MohamadOday** [comment]
i have the same issue

**Comment by leonheess** [comment]
@MohamadOday I think PGet has been abandoned

**Comment by halilozercan** [comment]
I've never meant to abandon this project but it has been so long since I last wrote a single line of Python. I'd be happy to accept a PR or even go through the whole process of transferring the ownership of this project (no idea how PyPi transfers are done).

**Comment by didadida-r** [comment]
pip install pget==0.5.1 can fix this bug.
