### ISSUE TITLE
Releases 0.5 and 0.5.0 are the same for `pip`

### ISSUE THREAD

**Issue by mpvvliet** [halilozercan/paralleldownload#14]
I have a project using `pget` that I want to use release `0.5.0`. However, no matter how I try to specify the dependencies, `pip` continues to install `0.5` instead of `0.5.0`.

Can someone re-release `0.5.0` as `0.5.1` or `0.6.0` so I can use the correct version?

Thanks,
Martin

**Comment by halilozercan** [comment]
https://pypi.org/project/PGet/0.5.1/
