### ISSUE TITLE
Support for hls streams

### ISSUE THREAD

**Issue by vn-ki** [halilozercan/paralleldownload#2]
This tool is the only fast pure python lightweight download I could find.

I would like to use this in a project of mine but I need support for downloading hls (m3u8) streams.

Can you look into it?

**Comment by halilozercan** [comment]
HLS stream download might be a bit different than what PGet is about. PGet simply opens concurrent connections from different ranges to a single HTTP/S endpoint. HLS on the other hand is a collection of different endpoints. HLS download might be out of the scope for this downloader.

**Comment by vn-ki** [comment]
That's sad. :(

It's okay nonetheless. Thank you for the awesome package.
