### ISSUE TITLE
What is callback, callback_threshold?

### ISSUE THREAD

**Issue by rvalenzuelar** [halilozercan/paralleldownload#7]
I'm not sure how to define callback and callback_threshold arguments. It is not clear from the help.

**Comment by halilozercan** [comment]
callback is a _callable_ which is called at every _callback_threshold_ bytes downloaded. You can think of it like a progress updater. Developers can use it to get regular updates about the download process.

**Comment by rvalenzuelar** [comment]
Thanks for clarifying!
